/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package studentcollege;
import java.awt.Color;
import java.awt.Font;
import java.util.*;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author PRATHABAN
 */
public class MarkSheet extends javax.swing.JFrame {
    public int count=0;

    /**
     * Creates new form MarkSheet
     */
    public MarkSheet() {
        initComponents();
        theader();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        sub1 = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        sub3 = new javax.swing.JLabel();
        sub4 = new javax.swing.JLabel();
        sub5 = new javax.swing.JLabel();
        sub6 = new javax.swing.JLabel();
        sub2 = new javax.swing.JLabel();
        subject1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cgpares = new javax.swing.JTextField();
        subject2 = new javax.swing.JComboBox<>();
        subject3 = new javax.swing.JComboBox<>();
        subject4 = new javax.swing.JComboBox<>();
        subject5 = new javax.swing.JComboBox<>();
        subject6 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        delete = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        save = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        view = new javax.swing.JButton();
        selectsem = new javax.swing.JComboBox<>();
        print = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setForeground(new java.awt.Color(204, 204, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1369, 765));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(153, 153, 153)));

        sub1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sub1.setText("MC4111                  :");
        sub1.setToolTipText("");

        uname.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        uname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                unameKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Register Number   :");
        jLabel4.setToolTipText("");

        sub3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sub3.setText("MC4113                  :");
        sub3.setToolTipText("");

        sub4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sub4.setText("MC4114                  :");
        sub4.setToolTipText("");

        sub5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sub5.setText("MC4115                  :");
        sub5.setToolTipText("");

        sub6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sub6.setText("MC4116                  :");
        sub6.setToolTipText("");

        sub2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sub2.setText("MC4112                  :");
        sub2.setToolTipText("");

        subject1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        subject1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT GRADE(7-10)", "10", "9", "8", "7" }));
        subject1.setToolTipText("");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("CGPA                      :");
        jLabel10.setToolTipText("");

        cgpares.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        cgpares.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cgparesFocusGained(evt);
            }
        });
        cgpares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cgparesActionPerformed(evt);
            }
        });

        subject2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        subject2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT GRADE(7-10)", "10", "9", "8", "7" }));
        subject2.setToolTipText("");

        subject3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        subject3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT GRADE(7-10)", "10", "9", "8", "7" }));
        subject3.setToolTipText("");

        subject4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        subject4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT GRADE(7-10)", "10", "9", "8", "7" }));
        subject4.setToolTipText("");

        subject5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        subject5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT GRADE(7-10)", "10", "9", "8", "7" }));
        subject5.setToolTipText("");

        subject6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        subject6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT GRADE(7-10)", "10", "9", "8", "7" }));
        subject6.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sub2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sub6, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sub5, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sub4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sub3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sub1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(uname)
                    .addComponent(subject1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cgpares)
                    .addComponent(subject2, 0, 180, Short.MAX_VALUE)
                    .addComponent(subject3, 0, 180, Short.MAX_VALUE)
                    .addComponent(subject4, 0, 180, Short.MAX_VALUE)
                    .addComponent(subject5, 0, 180, Short.MAX_VALUE)
                    .addComponent(subject6, 0, 180, Short.MAX_VALUE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uname, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sub1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subject1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sub2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subject2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sub3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subject3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sub4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subject4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sub5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subject5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sub6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subject6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cgpares, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Students Details");
        jLabel2.setToolTipText("");

        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(153, 153, 153)));

        jTable1.setBackground(new java.awt.Color(204, 204, 255));
        jTable1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Reg No", "MC4111", "MC4112", "MC4113", "MC4114", "MC4115", "MC4116", "CGPA"
            }
        ));
        jTable1.setToolTipText("");
        jTable1.setColumnSelectionAllowed(true);
        jTable1.setRowHeight(30);
        jTable1.setRowMargin(4);
        jTable1.setSelectionBackground(new java.awt.Color(102, 102, 102));
        jTable1.setShowGrid(true);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 938, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(153, 153, 153)));

        delete.setBackground(new java.awt.Color(255, 153, 153));
        delete.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        delete.setText("Delete");
        delete.setToolTipText("");
        delete.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.black, java.awt.Color.black), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.black, java.awt.Color.black)));
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        update.setBackground(new java.awt.Color(153, 255, 204));
        update.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        update.setText("Update");
        update.setToolTipText("");
        update.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.black, java.awt.Color.black), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.black, java.awt.Color.black)));
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(153, 204, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jButton3.setText("Exit");
        jButton3.setToolTipText("");
        jButton3.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.black, java.awt.Color.black), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.black, java.awt.Color.black)));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        save.setBackground(new java.awt.Color(255, 255, 153));
        save.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        save.setText("Save");
        save.setToolTipText("");
        save.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.black, java.awt.Color.black), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.black, java.awt.Color.black)));
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saveMouseExited(evt);
            }
        });
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        reset.setBackground(new java.awt.Color(0, 255, 153));
        reset.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        reset.setText("Reset");
        reset.setToolTipText("");
        reset.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.black, java.awt.Color.black), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.black, java.awt.Color.black)));
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        view.setBackground(new java.awt.Color(153, 255, 153));
        view.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        view.setText("View");
        view.setToolTipText("");
        view.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.black, java.awt.Color.black), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.black, java.awt.Color.black)));
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(view, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(view, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(save, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        selectsem.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        selectsem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT SEMESTER", "SEMESTER 1", "SEMESTER 2", "SEMESTER 3" }));
        selectsem.setToolTipText("");
        selectsem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectsemActionPerformed(evt);
            }
        });

        print.setBackground(new java.awt.Color(204, 204, 255));
        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(selectsem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 3, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(401, 401, 401))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(print)
                                        .addGap(97, 97, 97))))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(selectsem, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(print))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_deleteActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_updateActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Menu m=new Menu();
        m.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        if(count!=0){
            try{
                
            if(!uname.getText().isEmpty()){ 
                Double.parseDouble(uname.getText().toString());
        if(count==1){
       try{Class.forName("com.mysql.cj.jdbc.Driver");
            
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/collegemanagement","root","prathab");
            PreparedStatement pst=con.prepareStatement("insert into sem1(Regno,MC4111,MC4112,MC4113,MC4114,MC4115,MC4116,cgpa) values (?,?,?,?,?,?,?,?)");
            pst.setString(1,uname.getText() );
            pst.setString(2,subject1.getSelectedItem().toString() );
            pst.setString(3,subject2.getSelectedItem().toString());
            pst.setString(4,subject3.getSelectedItem().toString() );
            pst.setString(5,subject4.getSelectedItem().toString() );
            pst.setString(6,subject5.getSelectedItem().toString() );
            pst.setString(7,subject6.getSelectedItem().toString() );
             pst.setString(8,cgpares.getText() );
            pst.executeUpdate();
            updatetable1();
            JOptionPane.showMessageDialog(rootPane, "Recorts Added Successfully","Success",JOptionPane.WARNING_MESSAGE);
            
           
                }
            catch(ClassNotFoundException ex)
        { 
       System.out.println("Class not found");
    }
    catch(SQLException ex)
    { 
       System.out.println("SQL Error"+ex);
       
    }
        }
            if(count==2){
       try{Class.forName("com.mysql.cj.jdbc.Driver");
            
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/collegemanagement","root","prathab");
            PreparedStatement pst=con.prepareStatement("insert into sem2(Regno,MC4221,MC4222,MC4223,MC4224,MC4225,MC4226,cgpa) values (?,?,?,?,?,?,?,?)");
            pst.setString(1,uname.getText() );
            pst.setString(2,subject1.getSelectedItem().toString() );
            pst.setString(3,subject2.getSelectedItem().toString());
            pst.setString(4,subject3.getSelectedItem().toString() );
            pst.setString(5,subject4.getSelectedItem().toString() );
            pst.setString(6,subject5.getSelectedItem().toString() );
            pst.setString(7,subject6.getSelectedItem().toString() );
             pst.setString(8,cgpares.getText() );
            pst.executeUpdate();
            updatetable2();
            JOptionPane.showMessageDialog(rootPane, "Recorts Added Successfully","Success",JOptionPane.WARNING_MESSAGE);
            
           
                }
            catch(ClassNotFoundException ex)
        { 
       System.out.println("Class not found");
    }
    catch(SQLException ex)
    { 
       System.out.println("SQL Error"+ex);
       
    }
        }
            if(count==3){
       try{Class.forName("com.mysql.cj.jdbc.Driver");
            
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/collegemanagement","root","prathab");
            PreparedStatement pst=con.prepareStatement("insert into sem3(Regno,MC4331,MC4332,MC4333,MC4334,MC4335,MC4336,cgpa) values (?,?,?,?,?,?,?,?)");
            pst.setString(1,uname.getText() );
            pst.setString(2,subject1.getSelectedItem().toString() );
            pst.setString(3,subject2.getSelectedItem().toString());
            pst.setString(4,subject3.getSelectedItem().toString() );
            pst.setString(5,subject4.getSelectedItem().toString() );
            pst.setString(6,subject5.getSelectedItem().toString() );
            pst.setString(7,subject6.getSelectedItem().toString() );
             pst.setString(8,cgpares.getText() );
            pst.executeUpdate();
            updatetable3();
            JOptionPane.showMessageDialog(rootPane, "Recorts Added Successfully","Success",JOptionPane.WARNING_MESSAGE);
            
           
                }
            catch(ClassNotFoundException ex)
        { 
       System.out.println("Class not found");
    }
    catch(SQLException ex)
    { 
       System.out.println("SQL Error"+ex);
       
    }
        }
        
            }
        else{
            JOptionPane.showMessageDialog(rootPane, "Enter Register Number");
        
        }
        }
            catch(Exception e){
                JOptionPane.showMessageDialog(rootPane, "Plz Enter Valid Reg No");
                }
        }
        
        else{
            JOptionPane.showMessageDialog(rootPane, "Select Semester");
        }
        
        
        
        
       
    }//GEN-LAST:event_saveActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
       

    }//GEN-LAST:event_resetActionPerformed

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
                    if(count==0){
                        JOptionPane.showMessageDialog(rootPane, "Please Select Semester");
                    }
                    if(count==1){
                        updatetable1();
                    }
                    if(count==2){
                        updatetable2();
                    }
                    if(count==3){
                         updatetable3();
                    }
                    

        // TODO add your handling code here:
    }//GEN-LAST:event_viewActionPerformed

    private void selectsemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectsemActionPerformed
        // TODO add your handling code here:
            String h=selectsem.getSelectedItem().toString();
            if(h.equals("SELECT SEMESTER")){
                count=0;
            }
            
        if(h.equals("SEMESTER 1")){
            sub1.setText("MC4111");
            sub2.setText("MC4112");
            sub3.setText("MC4113");
            sub4.setText("MC4114");
            sub5.setText("MC4115");
            sub6.setText("MC4116");
            count=1;
        }
        if(h.equals("SEMESTER 2")){
            sub1.setText("MC4221");
            sub2.setText("MC4222");
            sub3.setText("MC4223");
            sub4.setText("MC4224");
            sub5.setText("MC4225");
            sub6.setText("MC4226");
         // Calendar c=Calendar.getInstance();
          // System.out.println(c.get(Calendar.DATE)+"/"+c.get(Calendar.MONTH)+"/"+c.get(Calendar.YEAR));
           //jTable1.getTableHeader().
            count=2;
            
        }
        if(h.equals("SEMESTER 3")){
            sub1.setText("MC4331");
            sub2.setText("MC4332");
            sub3.setText("MC4333");
            sub4.setText("MC4334");
            sub5.setText("MC4335");
            sub6.setText("MC4336");
             //jTable1.getTableHeader().getColumnModel().getColumn(0).setHeaderValue("MC4331");
            count=3;
        }
    }//GEN-LAST:event_selectsemActionPerformed

    private void cgparesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cgparesActionPerformed
        // TODO add your handling code here:
        Float k=(Float.parseFloat(subject1.getSelectedItem().toString())+Float.parseFloat(subject2.getSelectedItem().toString())+Float.parseFloat(subject3.getSelectedItem().toString())+Float.parseFloat(subject4.getSelectedItem().toString())+Float.parseFloat(subject5.getSelectedItem().toString())+Float.parseFloat(subject6.getSelectedItem().toString()))/6;
        cgpares.setText(String.valueOf(k));
    }//GEN-LAST:event_cgparesActionPerformed

    private void cgparesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cgparesFocusGained
        // TODO add your handling code here:
        Float k=(Float.parseFloat(subject1.getSelectedItem().toString())+Float.parseFloat(subject2.getSelectedItem().toString())+Float.parseFloat(subject3.getSelectedItem().toString())+Float.parseFloat(subject4.getSelectedItem().toString())+Float.parseFloat(subject5.getSelectedItem().toString())+Float.parseFloat(subject6.getSelectedItem().toString()))/6;
        cgpares.setText(String.valueOf(k));
    }//GEN-LAST:event_cgparesFocusGained

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed

   try{
       
       jTable1.print(JTable.PrintMode.FIT_WIDTH);
   }
   catch(java.awt.print.PrinterException e){
       System.err.format("Cannot print %s%n", e.getMessage());
       
   }
    
    }//GEN-LAST:event_printActionPerformed

    private void unameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unameKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(Character.isLetter(c) && !evt.isAltDown())
        {
            evt.consume();
        }
    }//GEN-LAST:event_unameKeyTyped

    private void saveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseEntered
        // TODO add your handling code here:
        save.setBackground(Color.WHITE);
    }//GEN-LAST:event_saveMouseEntered

    private void saveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseExited
        // TODO add your handling code here:
        save.setBackground(new Color(255,255,153));
    }//GEN-LAST:event_saveMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MarkSheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MarkSheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MarkSheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MarkSheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MarkSheet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cgpares;
    private javax.swing.JButton delete;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton print;
    private javax.swing.JButton reset;
    private javax.swing.JButton save;
    private javax.swing.JComboBox<String> selectsem;
    private javax.swing.JLabel sub1;
    private javax.swing.JLabel sub2;
    private javax.swing.JLabel sub3;
    private javax.swing.JLabel sub4;
    private javax.swing.JLabel sub5;
    private javax.swing.JLabel sub6;
    private javax.swing.JComboBox<String> subject1;
    private javax.swing.JComboBox<String> subject2;
    private javax.swing.JComboBox<String> subject3;
    private javax.swing.JComboBox<String> subject4;
    private javax.swing.JComboBox<String> subject5;
    private javax.swing.JComboBox<String> subject6;
    private javax.swing.JTextField uname;
    private javax.swing.JButton update;
    private javax.swing.JButton view;
    // End of variables declaration//GEN-END:variables

    private void updatetable1() {
   int cc;
        try{Class.forName("com.mysql.cj.jdbc.Driver");
       Connection con=DriverManager.getConnection("jdbc:mysql://localhost/collegemanagement","root","prathab");
       System.out.println("Connection Success for TableView");
       PreparedStatement pst=con.prepareStatement("select * from sem1");
       ResultSet rs=pst.executeQuery();
       ResultSetMetaData RSMD=rs.getMetaData();
       cc = RSMD.getColumnCount();
       DefaultTableModel DFT = (DefaultTableModel) jTable1.getModel();
       DFT.setRowCount(0);
        while(rs.next())
            {
                Vector v2=new Vector();
                
                for(int i=1;i<=cc;i++)
                {
                    v2.add(rs.getString("Regno"));
                    v2.add(rs.getString("MC4111"));
                     v2.add(rs.getString("MC4112"));
                    v2.add(rs.getString("MC4113"));
                    v2.add(rs.getString("MC4114"));
                    v2.add(rs.getString("MC4115"));
                    v2.add(rs.getString("MC4116"));
                    v2.add(rs.getString("cgpa"));
                }
                DFT.addRow(v2);
                
                
            }
    
    }catch(ClassNotFoundException ex)
    { 
       System.out.println("Class not found/Table not retreived");
    }
    catch(SQLException ex)
    { 
       System.out.println("SQL Error");
    } 
    }

    private void updatetable2() {
    int cc;
        try{Class.forName("com.mysql.cj.jdbc.Driver");
       Connection con=DriverManager.getConnection("jdbc:mysql://localhost/collegemanagement","root","prathab");
       System.out.println("Connection Success for TableView");
       PreparedStatement pst=con.prepareStatement("select * from sem2");
       ResultSet rs=pst.executeQuery();
       ResultSetMetaData RSMD=rs.getMetaData();
       cc = RSMD.getColumnCount();
       DefaultTableModel DFT = (DefaultTableModel) jTable1.getModel();
       DFT.setRowCount(0);
        while(rs.next())
            {
                Vector v2=new Vector();
                
                for(int i=1;i<=cc;i++)
                {
                    v2.add(rs.getString("Regno"));
                    v2.add(rs.getString("MC4221"));
                     v2.add(rs.getString("MC4222"));
                    v2.add(rs.getString("MC4223"));
                    v2.add(rs.getString("MC4224"));
                    v2.add(rs.getString("MC4225"));
                    v2.add(rs.getString("MC4226"));
                    v2.add(rs.getString("cgpa"));
                }
                DFT.addRow(v2);
                
                
            }
    
    }catch(ClassNotFoundException ex)
    { 
       System.out.println("Class not found/Table not retreived");
    }
    catch(SQLException ex)
    { 
       System.out.println("SQL Error");
    }  }

    private void updatetable3() {
     int cc;
        try{Class.forName("com.mysql.cj.jdbc.Driver");
       Connection con=DriverManager.getConnection("jdbc:mysql://localhost/collegemanagement","root","prathab");
       System.out.println("Connection Success for TableView");
       PreparedStatement pst=con.prepareStatement("select * from sem3");
       ResultSet rs=pst.executeQuery();
       ResultSetMetaData RSMD=rs.getMetaData();
       cc = RSMD.getColumnCount();
       DefaultTableModel DFT = (DefaultTableModel) jTable1.getModel();
       DFT.setRowCount(0);
        while(rs.next())
            {
                Vector v2=new Vector();
                
                for(int i=1;i<=cc;i++)
                {
                    v2.add(rs.getString("Regno"));
                    v2.add(rs.getString("MC4331"));
                     v2.add(rs.getString("MC4332"));
                    v2.add(rs.getString("MC4333"));
                    v2.add(rs.getString("MC4334"));
                    v2.add(rs.getString("MC4335"));
                    v2.add(rs.getString("MC4336"));
                    v2.add(rs.getString("cgpa"));
                }
                DFT.addRow(v2);
                
                
            }
    
    }catch(ClassNotFoundException ex)
    { 
       System.out.println("Class not found/Table not retreived");
    }
    catch(SQLException ex)
    { 
       System.out.println("SQL Error");
    }}

    private void theader() {
    
    JTableHeader thead=jTable1.getTableHeader();
    thead.setForeground(Color.BLACK);
    thead.setFont(new Font("Tahome",Font.BOLD,18));
   
    
    
    }
}
